version: '3.1'
services:
  API:
    image: 'drone'
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=PostgreSQL

  PostgreSQL:
    image: postgres:14.1-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5