server:
  port: ${SERVER_PORT}
spring:
  config:
    import: optional:file:.env[.properties]
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?createDatabaseIfNotExist=false&useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:sql/drones.sql, classpath:sql/medication.sql
      mode: always